### ISSUE TITLE
Ur code bad

### ISSUE THREAD

**Issue by emmachase** [Kristify/Kristly#2] opened 2022-12-24 00:43 UTC
https://github.com/Kristify/Kristly/blob/28ccfb7799d8c325a9d9efdd582d57f86b40d38b/src/kristly.lua#L397

https://krist.dev/docs/#:~:text=id%20should%20be%20a%20unique%2C%20automatically%20incrementing%20integer.

**Comment by Lustyn** [comment] 2022-12-24 00:46
for inspiration please see my extremely lazy code from 5 years ago: https://github.com/tmpim/k.lua/blob/master/k.lua#LL194-L198C4

**Comment by emmachase** [comment] 2022-12-24 00:47
extremely correct** code

**Comment by piprett** [comment] 2022-12-24 06:25
Thanks for pointing out our profesional code. This will be fixed, was already on my todo list. But it is not the most important thing we have to do. Currently we are working on a krist shop, which we have a deadline of 2022 on.

**Comment by Lemmmy** [comment] 2022-12-24 06:27
I'd love to know what made you think it needs to be random when the docs say it should be an incrementing integer. This will cause you problems

**Comment by piprett** [comment] 2022-12-24 06:31
I probably misread the documentation I am assuming. I checked in on the documentation now, and it does say "automatically incrementing integer". Will be fixed, along with the amount of trash EmmyLua- and normal- documentation.

**Comment by Lemmmy** [comment] 2022-12-24 06:33
Sounds good. Because the Krist server has no guarantee that it will accept a floating point number, and anything that isn't monotonic (e.g. a PRNG) will result in unexpected behavior when handling websocket responses

**Comment by piprett** [comment] 2022-12-24 07:35
Thanks for reminding me of the issue. There should be some new stuff coming soon™ too. If issues with the auto incrementing please re-open the issue.

**Closed as completed by piprett** 2022-12-24 07:35 UTC
